# Trigger on pull request to master (+ allow manual runs of this workflow)
# Checkout repo, install Node.js, run test

name: pr-workflow

on:
# [to be filled]
  pull_request:
    branches:
    - master
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    # [to be filled]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3 #name: Install Node.js
        with:
          node-version: 14
        # [rest to be filled]
      - name: run test
        uses: npm test
